# Site settings
title:          The Dynasty League
description:    "A website for the best fanstasy football league around"
baseurl:        "/"
url:            "https://dynastyleague.football"

# Author
author:
  name:         swoicik
  url:          https://swoicik.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year/:title
paginate:       8

# Pages
include: ['_pages']

